### ISSUE TITLE
Uniform theme for whole app

### ISSUE THREAD

**Issue by vbkristof** [Hollo-Event-Notifier/Hollo-Event-Notifier-App#31]
# Requirements
Uniform theme rules shall exist for the whole application.

# Solution
The following documentations can help you:
- https://material.angular.io/guide/theming
- https://fullcalendar.io/docs/theming
- https://m3.material.io/get-started

# Acceptance criteria
- Theme rules like colors, typography, icons etc. should be defined
- Theme rules shall be implemented as a theme for angular material
- The rules implemented in the theme should be also used to theme the `full-calendar` component, which is based on bootstrap

**Comment by AndrasFerenczy** [comment]
Closed with the following pull request: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/pull/41

**Comment by AndrasFerenczy** [comment]
Closed with the following pull request: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/pull/41
