### ISSUE TITLE
CI - Test backend & code coverage report

### ISSUE THREAD

**Issue by AndrasFerenczy** [Hollo-Event-Notifier/Hollo-Event-Notifier-App#49]
### Requirements
Implement the testing of backend in the CI, and create a code coverage report (both with JUnit 5)

### Solution

1. First of all, read why and how we would like to use CI: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/issues/8
2. Then have a look at a basic example where the frontent build is tested to see how Github Actions work: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/actions/runs/4973020903
3. and at the workflow file: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/actions/runs/4973020903/workflow
4. Implement the testing of the backend (./gradlew test) as a **seperate job** which only runs after the **build** testing is done (hint: https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed). Modify the in the validation.yml file in the **branch linked** to this issue. 
5. Implement the testing so that a coverage report is generated.

### Acceptance criteria

- A proper working yml file which runs the backend tests.
- A successful workflow should be made to demonstrate the working of the pipeline with the new feature.
- A code coverage report should be generated.

### Hints
Have a look at the documentation: https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
ChatGPT can help you a lot!

**Comment by benhorv** [comment]
- added JaCoCo to the gradle project for coverage report generation

**Comment by benhorv** [comment]
Merged PR
