### ISSUE TITLE
CI - Test frontend & code coverage report

### ISSUE THREAD

**Issue by AndrasFerenczy** [Hollo-Event-Notifier/Hollo-Event-Notifier-App#50]
### Requirements
Implement the testing of frontend in the CI, and create a code coverage report

### Solution

1. First of all, read why and how we would like to use CI: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/issues/8
2. Then have a look at a basic example where the frontent build is tested to see how Github Actions work: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/actions/runs/4973020903
3. and at the workflow file: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/actions/runs/4973020903/workflow
4. Implement the testing of the frontend as a **seperate job** which only runs after the **build** testing is done (hint: https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed). Modify the validation.yml file in the **branch linked** to this issue. 
5. Implement the testing so that a coverage report is generated. (ng test --code-coverage)

### Acceptance criteria

- A proper working yml file which runs the frontend tests.
- A successful workflow should be made to demonstrate the working of the pipeline with the new feature.
- A code coverage report should be generated.

### Hints
Have a look at the documentation: https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
ChatGPT can help you a lot!

**Comment by benhorv** [comment]
Merged PR
