### ISSUE TITLE
CI - Upload report to code analyzer tool

### ISSUE THREAD

**Issue by AndrasFerenczy** [Hollo-Event-Notifier/Hollo-Event-Notifier-App#51]
### Requirements
Once the testing is done on both backend and frontend, upload the reports to a code analyzer tool (sonarcloud). 

### Solution

1. First of all, read why and how we would like to use CI: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/issues/8
2. Then have a look at a basic example where the frontent build is tested to see how Github Actions work: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/actions/runs/4973020903
3. and at the workflow file: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/actions/runs/4973020903/workflow
4. Implement the uploading of the report to a code analyzer tool, such as Sonarcloud as a **seperate job** which only runs after the **testing** is done (hint: https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed). Modify the in the validation.yml file in the **branch linked** to this issue. 

### Acceptance criteria

- A proper working yml file which uploads the report sonarcloud
- A successful workflow should be made to demonstrate the working of the pipeline with the new feature.

### Hints
Sonarcloud: https://github.com/SonarSource/sonarcloud-github-action
Have a look at the documentation of GitHub Actions: https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
ChatGPT can help you a lot!

**Comment by AndrasFerenczy** [comment]
Redundant with: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/issues/46

**Comment by vbkristof** [comment]
In addition you should connect the sonarcloud instance to GH actions!

**Comment by PeterH001** [comment]
I have more problems:

- In sonar cloud when clicking on "Analyze new project" buton I can not add this project, perhaps because I am not the organisation owner:

![Image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/326e3d8a-3023-4637-b0d8-88ed9b617a92)

- furthermore the github actions failed and do not know, how should I fix this error:

![Image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/4149ef45-949d-41ec-9969-7b2e69eecc85)

I am assuming, that the problem is that the gradle files are not in the root directory of the project(?) again I am not sure and I am stuck.

It is possible, that the first one is not a real problem at all and the results would appear if the github actions job ran correctly, because the organization is already connected with sonar cloud.
I am left with these questionmarks and I can not go further.

**Comment by vbkristof** [comment]
> I have more problems:
> 
> * In sonar cloud when clicking on "Analyze new project" buton I can not add this project, perhaps because I am not the organisation owner:
> 
> ![Image](https://user-images.githubusercontent.com/79469445/238751623-326e3d8a-3023-4637-b0d8-88ed9b617a92.png)
> 
> * furthermore the github actions failed and do not know, how should I fix this error:
> 
> ![Image](https://user-images.githubusercontent.com/79469445/238752072-4149ef45-949d-41ec-9969-7b2e69eecc85.png)
> 
> I am assuming, that the problem is that the gradle files are not in the root directory of the project(?) again I am not sure and I am stuck.
> 
> It is possible, that the first one is not a real problem at all and the results would appear if the github actions job ran correctly, because the organization is already connected with sonar cloud. I am left with these questionmarks and I can not go further.

1. A projektet mikor akarod importálni? Te ha ezt megnyitod mit látsz? Sztem én már behúztam sonarcloud-ba az egészet, lehet csak nem látod még.
https://sonarcloud.io/project/configuration?id=Hollo-Event-Notifier_Hollo-Event-Notifier-App

2. Ott az a gond, hogy a `backend` mappában kéne futtatni a build-et. Most vagy be `cd`-zel oda, vagy valahogy bejuttatod oda a shell-t. Asszem ezt andris megoldotta vmi prefix-eléssel a frontend build-nél. Az egy jó alap lehet.

**Comment by PeterH001** [comment]
![Image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/b61170c2-08b1-477f-be05-8a6c00691b70)

Ezt látom.

Mikor laboron ezt csináltuk, hogy lássunk analízis eredményeket, ki kellett választani egy projektet. Az analize new project gombra kattintva ez fogad:


![Image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/d1d569f8-b5d2-420b-b1bc-dfd92395ed76)

Teljesen jogosan, hiszen azt a projektet már importáltam és az az importált projektnek így kellene kinéznie:


![Image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/ca954ccd-9009-4290-b6ab-bf7ae6679263)


Akkor is, ha csak beimportáltam, de még nem futtattam rajta semmilyen analízist.

Namármost ugyanezt a lépéssorozatot nem tudom reprodukálni a jelenlegi projekttel.


A második ponton még dolgozom.

**Comment by vbkristof** [comment]
> ![Image](https://user-images.githubusercontent.com/79469445/239011886-b61170c2-08b1-477f-be05-8a6c00691b70.png)
> 
> Ezt látom.
> 
> Mikor laboron ezt csináltuk, hogy lássunk analízis eredményeket, ki kellett választani egy projektet. Az analize new project gombra kattintva ez fogad:
> 
> ![Image](https://user-images.githubusercontent.com/79469445/239012522-d1d569f8-b5d2-420b-b1bc-dfd92395ed76.png)
> 
> Teljesen jogosan, hiszen azt a projektet már importáltam és az az importált projektnek így kellene kinéznie:
> 
> ![Image](https://user-images.githubusercontent.com/79469445/239012841-ca954ccd-9009-4290-b6ab-bf7ae6679263.png)
> 
> Akkor is, ha csak beimportáltam, de még nem futtattam rajta semmilyen analízist.
> 
> Namármost ugyanezt a lépéssorozatot nem tudom reprodukálni a jelenlegi projekttel.
> 
> A második ponton még dolgozom.

Mivel már be van importálva a projekt ezért nem tudod frissen analizálni. Sztem amit te akarsz az inkább itt az administrations -> analyze method nem?


![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/122607148/d430ed0f-9caf-445f-b40d-e4be1699cc60)

Hiszen itt lehet CI-t rákötni.

**Comment by PeterH001** [comment]
Beimportálva be van, de nincs analizálva. 

![Image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/d199aecf-5267-4c4c-8953-5a7120956b7f)

 Én nem beimportálni akarom, hanem analizálni. És nem tudom kiválasztani ezt a projektet analizálásra. A gomb, ami a screenshotodon van, az pedig nekem nincs is a kezelőfelületemen. Valószínűleg nincsenek meg a megfelelő jogosultságaim.

![Image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/d304a731-df11-4477-b548-df99b88753c1)



![Image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/a3b03259-732f-46ed-86e9-a0115f45da18)

**Comment by vbkristof** [comment]
> Beimportálva be van, de nincs analizálva.
> 
> ![Image](https://user-images.githubusercontent.com/79469445/239759319-d199aecf-5267-4c4c-8953-5a7120956b7f.png)
> 
> Én nem beimportálni akarom, hanem analizálni. És nem tudom kiválasztani ezt a projektet analizálásra. A gomb, ami a screenshotodon van, az pedig nekem nincs is a kezelőfelületemen. Valószínűleg nincsenek meg a megfelelő jogosultságaim.
> 
> ![Image](https://user-images.githubusercontent.com/79469445/239759192-d304a731-df11-4477-b548-df99b88753c1.png)
> 
> ![Image](https://user-images.githubusercontent.com/79469445/239759230-a3b03259-732f-46ed-86e9-a0115f45da18.png)

Mostmár owner vagy ott is, megnézed így?

**Comment by PeterH001** [comment]
Oké, tényleg, mostmár megvannak a jogosultságaim, tényleg nem tudom beimportálni újra. De legalább egy zsákutcát kizártunk. @vbkristof

**Comment by PeterH001** [comment]
Mikor lefutottak a Github Actions feladatok feltűnt, hogy a Sonarcloudban nem jelennek meg a frontend fileok.
Ezért kitöröltem azt a feladatot, amely a backendet tölti fel, így aztán megjelent MINDEN file sonacloudban, a fronted és a backend egyaránt és mindent analizált. Szóval kitöröltem azt a jobot, így egy maradt, amire eredetileg azt gondoltam, hogy a frontendet fogja csupán feltölteni. 

Csatolok ide screenshotokat először arról, hogy mit láttam Sonarcloudban, amikor mind a kettő feladat lefutott és mit akkor, amikor csak az egyik (az analize frontend, amit végül bennehagytam):
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/1a3d20b8-bb08-424b-b7f2-7260217f72a2)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/9111b1bc-8000-43d7-a115-32794849459a)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/9509f085-c811-45d0-8adf-7534228160f0)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/2d370c06-acf2-4769-80b6-db7830346151)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/3ee1bdbc-05e6-40a7-9713-bb196f81d638)

--------------------------------

![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/cc655fa0-d59e-404d-a584-834c1271c99b)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/65fbba04-a343-470a-91b8-0ab14c238e05)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/39a116c4-9337-4ee0-bb14-3cecec3778c3)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/75c34c31-85b5-4f37-b41a-3c340609bf5d)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/172ff3c5-2784-42d0-b9b2-557b63c138da)


Látható, hogy a második képsorozaton mennyivel több kód és egyéb infó jelent meg.
Összességében tehát egy 15 peres feladatot bonyolítottam túl ilyen hosszan. Legalább megtanultam ezt is.
