### ISSUE TITLE
Stress testing - Goals and scenarios

### ISSUE THREAD

**Issue by benhorv** [Hollo-Event-Notifier/Hollo-Event-Notifier-App#53]
# Requirements

- We should have a set of performance goals.
    - That includes concurrent user count and responsiveness of the application.
    - This should not be very exact.
- We should have a set of scenarios, which could be tested.
 - Have at least 2-3 test cases.

# Solution

- Collect the information above and document them.

# Acceptance criteria

- Have the above documented and reviewed by someone.

**Comment by benhorv** [comment]
#### Scenarios

Since the number of implemented requests is not so high, implementing stress tests for each one should not be very difficult.

Requests:

`POST /users/login`
`GET /users/check-token`
`GET /events`
`PUT /events`
`GET /events/{id}`
`POST /events/{id}`
`DELETE /events/{id}`

#### Goals

Due to the nature of stress testing, our goals can not be very well defined in this state of development. In most cases stress tests depend on the hardware on which the app is running. But despite of this fact, we can define some general requirements for our use case.

This application should serve around **100 users concurrently**, and each request should arrive within **50ms**.

**Comment by vbkristof** [comment]
> #### Scenarios
> Since the number of implemented requests is not so high, implementing stress tests for each one should not be very difficult.
> 
> Requests:
> 
> `POST /users/login` `GET /users/check-token` `GET /events` `PUT /events` `GET /events/{id}` `POST /events/{id}` `DELETE /events/{id}`
> 
> #### Goals
> Due to the nature of stress testing, our goals can not be very well defined in this state of development. In most cases stress tests depend on the hardware on which the app is running. But despite of this fact, we can define some general requirements for our use case.
> 
> This application should serve around **100 users concurrently**, and each request should arrive within **50ms**.

Seems good to me, I think we should start implementing them.
