### ISSUE TITLE
Stress testing - Set up JMeter

### ISSUE THREAD

**Issue by benhorv** [Hollo-Event-Notifier/Hollo-Event-Notifier-App#59]
# Requirements

- JMeter should be ready for testing

# Solution

- Look for how JMeter could be utilized
- Set up JMeter as a program
- Set up environment to be able to run tests on our project

# Acceptance criteria

- JMeter is ready to use
- At least one dummy test case is runnable

**Comment by vbkristof** [comment]
- create stress_testing folder
- sample test file
- readme.md about how to run and create new tests
