### ISSUE TITLE
Set up Cucumber test framework

### ISSUE THREAD

**Issue by PeterH001** [Hollo-Event-Notifier/Hollo-Event-Notifier-App#62]
<https://cucumber.io/docs/installation/>

Introduction:

<https://school.cucumber.io/courses/bdd-with-cucumber-javascript>

**Comment by vbkristof** [comment]
<https://github.com/hdorgeval/cucumber7-ts-starter>
<https://www.npmjs.com/package/cucumber-tsflow>
