### ISSUE TITLE
Setup of CI Task

### ISSUE THREAD

**Issue by vbkristof** [Hollo-Event-Notifier/Hollo-Event-Notifier-App#8]
# Requirements
You should make a research about github actions and plan how to solve the following tasks in the pipeline:
- creation of **build step**: Checks if the projects compiles without errors
- creation of **unit test step**: Runs all unit tests and creates a coverage report
- creation of **report upload step**: Uploads the created coverage reports to a code analyzer tool (e.g.: Sonarcube), this step is connection with: [Setup of unit testing and coverage task](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/issues/42)
- *Optional:* creation of **docker image builder step**: This step creates all neccessary docker images to deploy our application. In advance these are the following:
  - Backend image: containing the compiled kotlin spring application
  - Frontendd image: containing the compiled frontend application in a webserver (e.g.: nginx)
  - Some deployment decisions are needed, if 

In addition to that please create a documentation markdown file in the docs folder. This file will contain our documentation for this task for the IET homework.

You should also think about the following things:
- on which trigger should a step run (e.g.: every push, PR opened, merge etc)
- on which branch should a step run (e.g.: build and unit tests are running on all branches, but ddocker image builder runs only on master since the other branches doesn't deliver increments)

# Solution
Please make a research about this task and create all neccessary tickets, in addition to that please document your work here as a comment.

# Acceptance criteria
- The tickets describing all separate tasks should exist.
- The markdown file should exist
- The comments here in the ticket about your work should exist

# Deadline
Please complete this task until 2023.05.13. in order to have enough time to complete the other tasks.

**Comment by AndrasFerenczy** [comment]
1. A new branch was created (8-CI-Setup), where a demo GitHub Action was implemented to demonstrate how each job/step should be realised: 
- Workflow: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/actions/runs/4973020903
- YML: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/actions/runs/4973020903/workflow

2. Tickets were created for each seperate tasks:
- https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/issues/52
- https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/issues/51
- https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/issues/50
- https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/issues/49
- https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/issues/48

3. A documentation file was created where the improvements can be writen down later: https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/blob/8-CI-setup/docs/continous_integration_report.md
